# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[files]
extend-exclude = [
  # Microsoft Detours, vendored unmodified.
  "pnpm/crates/detours-sys/detours/**",
  "pnpm/crates/crypto-shasums-file/src/node_release_keys/*.asc",
  "pnpm/tasks/micro-benchmark/fixtures/lodash.json",
]

[default.extend-words]
cafs   = "cafs"
# `msghdr::msg_controllen`
controllen = "controllen"
ect    = "ect"
intoto = "intoto"
pn     = "pn"

[default.extend-identifiers]
PnP = "PnP"
